app/urls.py
from django.urls import path
from .views import home, about, serviceburenie, servicesverlenie, contact, ourwork, SearchResultsView
app_name = 'app'
urlpatterns = [
    path('', home, name='home'),
    path('search/', SearchResultsView.as_view(), name='search'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('ourwork', ourwork, name='ourwork'),
    path('service-burenie', serviceburenie, name='service-burenie'),
    path('service-sverlenie', servicesverlenie, name='service-sverlenie'),

]

welldrill/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    url = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'services'

    def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from .models import Service

def home(request):
    return render(request, 'app/home.html')
def about(request):
    return render(request, 'app/about.html')
def serviceburenie(request):
    return render(request, 'app/service-burenie.html')
def servicesverlenie(request):
    return render(request, 'app/service-sverlenie.html')
def contact(request):
    return render(request, 'app/contact.html')
def ourwork(request):
    return render(request, 'app/ourwork.html') 
class SearchResultsView(ListView):
    model = Service
    template_name = 'app/search.html'

    def get_queryset(self):
        query = (self.request.GET.get('q')).lower()
        object_list = Service.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
        return object_list

    # def get_queryset(self):
    #     return Service.objects.filter(
    #         name__icontains='е'
    #     ) .exclude(
    #         name__icontains='Бурение'
    #     )
    # def get_queryset(self):
    #     return Service.objects.filter(
    #         Q(name__icontains='Бурение') | Q(description__icontains='разных форм')
    #     )

app/templates/app/about.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="Мы бурим с 1830 года. Делаем дёшево, качественно, а главное - глубоко">
<title>О компании</title>
{% endblock head %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col about">
            <div class="about-description"><span class="colorful-2">О компании</span></div>
        </div>
    </div>
    <div class="container about-text mt-3">
        <h2> <span class="colorful" style="font-size: 40px;">WellDrill<span style="font-size:14px;vertical-align: top;">®</span></span> - крупнейшая бурильная компания на планете </h2>
        <p> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea tempore, delectus non alias impedit
            perspiciatis. Ipsa neque commodi iure sequi distinctio quis quam blanditiis quaerat doloribus delectus
            corrupti, enim eos.
            Nihil soluta nemo, quisquam est illo distinctio consectetur, quos quaerat ea aut nulla pariatur repellendus.
            Quia odio doloremque, omnis dignissimos, nostrum impedit mollitia numquam sint tempora fugit eos obcaecati
            quaerat?
            Quod odit accusamus voluptatibus repellat cumque nesciunt.</p>
        <p>Itaque quis et architecto repudiandae ipsam culpa laudantium necessitatibus nobis facilis quod dignissimos
            iusto eos pariatur, ea doloribus soluta sunt sequi! Iusto, illum.
            Facilis minus animi blanditiis aliquid nihil quasi veniam aut similique natus. Iste qui optio alias, eum
            perferendis earum possimus rem ullam corrupti cum fugit modi nam commodi laudantium eos dolore!
            Labore recusandae earum rerum illo.</p>
        <p>
            Voluptatum enim corrupti quos tenetur rem animi, voluptatem unde incidunt itaque repudiandae sint doloremque
            suscipit mollitia fugiat ut sunt sequi aliquid ipsum odio! Quos, sapiente.
            Rem nobis excepturi nisi facilis! Atque reprehenderit exercitationem quisquam asperiores illum dolorum
            facilis beatae aliquam laborum modi rem architecto reiciendis est dolores ipsa debitis, ratione facere
            tempore voluptates vel fuga?
            Illum maxime ut modi, eveniet aliquam nesciunt, numquam minima expedita doloribus, vitae dolor! Atque vel
            quis recusandae ratione unde obcaecati, aut inventore itaque. Soluta dolores odio quidem minima ab neque!
            Quidem temporibus voluptatem dolores mollitia quis itaque optio facere minus beatae iure, perspiciatis
            voluptates ut debitis laborum provident odit et hic. Debitis non fugiat provident veniam deserunt maxime est
            saepe.
            Aperiam voluptate inventore sed officia.
        </p>
        <p>
            Asperiores, quis quibusdam. Quae dolor sunt temporibus exercitationem laudantium distinctio, nihil vitae
            amet optio, qui sit deserunt fuga laboriosam, ad assumenda! Quibusdam itaque commodi aspernatur.
            Eligendi fugiat, quod architecto ea obcaecati corporis praesentium in, aliquam repellat, accusamus ex
            delectus aspernatur soluta eum at assumenda quibusdam fuga neque atque! Fugiat ipsum natus numquam quos,
            laudantium debitis.</p>

        </p>
    </div>
</div>
{% endblock content %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    {% block head %} {% endblock head %}
</head>

<body class="full-width">
    <div class="container-fluid">
        <div class="row my-menu">
            <div class="col ps-0 pe-0">
                <nav class="navbar navbar-expand-sm navbar-dark bg-dark full-width">
                    <a class="navbar-brand logo ps-3" href="{% url 'app:home' %}" style="color: #458AF1">WellDrill<span
                            style="font-size:18px;vertical-align: top;">®</span></a>
                    <div class="container-fluid">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="{% url 'app:home' %}">Главная</a>
                                <li class="divider d-none d-xxl-block"></li>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'app:about' %}">О компании</a>
                                <li class="divider d-none d-xxl-block"></li>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                        role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Услуги
                                    </a>
                                    <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                                        <li><a class="dropdown-item text-white test1" href="{% url 'app:service-burenie' %}">Бурение</a></li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li><a class="dropdown-item text-white test1" href="{% url 'app:service-sverlenie' %}">Сверление</a></li>
                                        <li>
                                    </ul>
                                </li>
                                <li class="divider d-none d-xxl-block"></li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'app:contact' %}">Контакты</a>
                                <li class="divider d-none d-xxl-block"></li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'app:ourwork' %}">Наши работы</a>
                                </li>
                            </ul>
                        </div>
                        <form action="{% url 'app:search' %}" method='get' class="d-flex d-none d-xl-flex">
                            <input name="q" class="form-control me-2" type="text" placeholder="Поиск по услугам" aria-label="Search">
                            <button class="btn btn-outline-secondary" type="submit">Найти</button>
                        </form>
                    </div>
                </nav>
            </div>
        </div>
    </div>

    {% block content %}{% endblock content %}
    <div class="container-fluid text-white bg-dark pt-4 mt-3 sticky-bottom">
        <div class="row">
            <div class="col">
                <div class="row d-block">
                    <div class="col mb-3 colorful" style="font-family:'Montserrat', sans-serif;color: #458AF1;font-size: 40px;">
                        WellDrill<span style="font-size:16px;vertical-align: top;">®</span></div>
                    <div class="col"> ОАО "WellDrill", <br>Энгельса 30, 367026, Махачкала</div>
                    <div class="col" style="color:aquamarine"> by Magomed Rabadanov </div>
                </div>
            </div>
            <div class="col-8 width-95">
                <div class="row">
                    <div class="ps-lg-5 col-lg-4 col-12 pt-4 pt-md-0 width-80">
                        <ul class="my-list">
                            
                                <li class="my-first-list" style="color:rgb(61, 113, 255)">Карта сайта</li>
                            
                            
                                <li class="list"><a href="">Главная</a></li>
                            
                            
                                <li class="list"><a href="{% url 'app:about' %}">О компании</a></li>
                            
                            <li class="list dropbtn" onclick="myFunction()">Услуги</li>
                            <div id="myDropdown" class="bottom-dropdown-content">
                                <a href="{% url 'app:service-burenie' %}">Бурение</a>
                                <a href="{% url 'app:service-sverlenie' %}">Сверление</a>
                              </div>
                            <li class="list"><a href="{% url 'app:contact' %}">Контакты</a></li>
                            <li class="list"><a href="{% url 'app:ourwork' %}">Наши работы</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-12 width-80">
                        <ul class="my-list">
                            <li class="my-first-list"><a href="{% url 'app:contact' %}" style="color:rgb(61, 113, 255)">Контакты</a></li>
                            <li class="list"><a href="tel:+79896535030">Телефон: +7 (989) 653 50 70</a></li>
                            <li class="list"><a href="mailto:detalikota@gmail.com">Email: detalikota@gmail.com</a></li>
                            <li class="list"><a href="https://wa.me/+79896535030">Whatsapp</a></li>
                            <li class="list"><a href="https://telegram.me/detalikota">Telegram</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-12 pe-lg-5 width-80">
                        <ul class="my-list">
                            <li class="my-first-list" style="color:rgb(61, 113, 255)">Социальные сети</li>
                            <li class="list"><a href="">VK</a></li>
                            <li class="list"><a href="">Instagram</a></li>
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    <script src="{% static 'app/bottom-dropdown.js' %}"></script>
    <script src="{% static 'app/autotext.js' %}"></script>
</body>

</html>

app/templates/app/contact.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="ОАО WellDrill, Энгельса 30, 367026, Махачкала. Телефон: +7 (989) 653 50 70. Почта: detalikota@gmail.com">
<title>Контактная информация компании WellDrill</title>
{% endblock head %}
{% block content %}
<div class="container-fluid ps-5 py-3" style="background: rgb(255,255,255);
background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgb(0, 132, 255) 100%);">
    <div class="container">
        <h1 style="font-weight: bold;">КОНТАКТНАЯ ИНФОРМАЦИЯ</h1>
    </div>
</div>
<div class="container about-text pt-3">
    <dl class="row">
        <dt class="col-sm-3">Адрес:</dt>
        <dd class="col-sm-9">ОАО "WellDrill", Энгельса 30, 367026, Махачкала</dd>
        <dt class="col-sm-3">Телефон:</dt>
        <dd class="col-sm-9"><a href="tel:+79896535030">+7 (989) 653 50 70 </a></dd>
        <dt class="col-sm-3">Email:</dt>
        <dd class="col-sm-9"><a href="mailto:detalikota@gmail.com">detalikota@gmail.com</a></dd>
        <dt class="col-sm-3">WhatsApp:</dt>
        <dd class="col-sm-9"><a href="https://wa.me/+79896535030">Написать</a></li>
        <dt class="col-sm-3">Telegram:</dt>
        <dd class="col-sm-9"><a href="https://telegram.me/detalikota">Написать</a></li>
      </dl>
</div>

<div class="container"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2919.353178018696!2d47.4802444157619!3d42.97083340430253!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x404ea15ce9e13f9f%3A0x42eb5720271dadf4!2sUlitsa%20Engel&#39;sa%2C%2030%2C%20Makhachkala%2C%20Respublika%20Dagestan%2C%20367015!5e0!3m2!1sen!2sru!4v1621256990741!5m2!1sen!2sru" width="100%" height="600" style="border:2px solid rgb(0, 183, 255);" allowfullscreen="" loading="lazy"></iframe></div>

{% endblock content %}

app/templates/app/home.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="WellDrill главная страница">
<title>WellDrill официальный веб-сайт</title>
{% endblock head %}
{% block content %}
<div class="container">
  <h1 id="auto-text" class="auto-text"></h1>
  <div id="carouselExampleCaptions" class="carousel slide mt-4 d-none d-md-block" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner rounded">
      <div class="carousel-item active my-bottom">
        <img src="{% static 'app/images/carousel-1.jpg' %}" class="d-block w-100" alt="Машина для бурения WellDrill">
        <div class="carousel-caption d-none d-md-block car-1">
          <h5 class="my-bg-grey">Бурим глубоко</h5>
          <p class="my-bg-grey">Мы бурим настолько глубоко, насколько это нужно</p>
        </div>
      </div>
      <div class="carousel-item my-bottom">
        <img src="{% static 'app/images/carousel-2.jpg' %}" class="d-block w-100"
          alt="Процесс бурения в компании WellDrill">
        <div class="carousel-caption d-none d-md-block car-2">
          <h5 class="my-bg-grey">Выкачиваем</h5>
          <p class="my-bg-grey">Выкачиваем из-под земли чистейшую воду</p>
        </div>
      </div>
      <div class="carousel-item my-bottom-2">
        <img src="{% static 'app/images/carousel-3.jpg' %}" class="d-block w-100" alt="Бурением скважины на воде">
        <div class="carousel-caption d-none d-md-block car-3">
          <h5 class="my-bg-grey">В любое время</h5>
          <p class="my-bg-grey">Работаем круглые сутки до результата</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row justify-content-center">
    
    <a href="{% url 'app:service-burenie' %}" class="no-underline col-3 fw-bold my-square me-3 rounded">
      <p class="my-square-text">БУРЕНИЕ</p>
      <p class="my-hover-text">Подробнее></p>
    </a>
    <a href="{% url 'app:service-sverlenie' %}" class="no-underline col-3 fw-bold my-square-2 me-3 rounded">
      
      <p class="my-square-text">Сверление</p>
      <p class="my-hover-text">Подробнее></p>
    
    </a>
    <div class="col-3 fw-bold my-square rounded">
      <p class="my-square-text">КАНАЛИЗАЦИЯ</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-3 fw-bold my-square-2 me-3 rounded">
      <p class="my-square-text">ОТОПЛЕНИЕ</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
    <div class="col-3 fw-bold my-square me-3 rounded">
      <p class="my-square-text">БУРЕНИЕ СКВАЖИН НА ВОДУ В РАССРОЧКУ</p>
      <p class="my-hover-text-2">(пока не кликабельно)</p>
    </div>
    <div class="col-3 fw-bold my-square-2 rounded">
      <p class="my-square-text">АРЕНДА ТЕХНИКИ</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-3 fw-bold my-square me-3 rounded">
      <p class="my-square-text">ВОДООЧИСТКА</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
    <div class="col-3 fw-bold my-square-2 me-3 rounded">
      <p class="my-square-text">СЕРВИСНОЕ ОБСЛУЖИВАНИЕ</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
    <div class="col-3 fw-bold my-square rounded">
      <p class="my-square-text">СТРОИТЕЛЬСТВО ДОМОВ</p>
      <p class="my-hover-text">(пока не кликабельно)</p>
    </div>
  </div>

</div>
{% endblock content %}

app/templates/app/ourwork.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="Вот такую работу мы проделали:">
<title>Наши работы</title>
{% endblock head %}
{% block content %}
<div class="container pt-3">
    <div class="row">
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            <img src="{% static 'app/images/carousel-1.jpg' %}"
                class="w-100 shadow-1-strong rounded mb-4" alt="Процедура бурения" />

            <img src="{% static 'app/images/horizon-1.jpg' %}"
                class="w-100 shadow-1-strong rounded mb-4" alt="Бурение скважины" />
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <img src="{% static 'app/images/horizon-2.jpg' %}"
                class="w-100 shadow-1-strong rounded mb-4" alt="Бурим скважину на воду" />

            <img src="{% static 'app/images/carousel-2.jpg' %}"
                class="w-100 shadow-1-strong rounded mb-4" alt="Well drilling" />
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <img src="{% static 'app/images/carousel-3.jpg' %}"
                class="w-100 shadow-1-strong rounded mb-4" alt="Water Well Drilling" />

            <img src="{% static 'app/images/horizon-3.jpeg' %}"
                class="w-100 shadow-1-strong rounded mb-4 horizon-3" alt="Бурение воды из-под земли" />
        </div>
    </div>
</div>


{% endblock content %}

app/templates/app/search.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="Выдача поискового запроса">
<title>Результаты поиска</title>
{% endblock head %}
{% block content %}
<div class="container search-container">
<h2> Результаты поиска по услугам:</h2>
<table class="table search-table">
    <thead>
        <tr>
            <th scope="col" style="font-size:18px;">Услуга</th>
            <th scope="col" style="font-size:18px;">Описание услуги</th>
        </tr>
    </thead>
    <tbody>

            {% for service in object_list %}
    <tr>
    <td><a href= {{ service.url }} class="search-link cap"> {{ service.name }}</a></td>
    <td class="cap">{{ service.description }}</td>
    </tr>
    {% endfor %}
        
    </tbody>
</table>

</div>
{% endblock content %}

app/templates/app/service-burenie.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="Бурение, водоснабжение, из колодца, на известняк, на песок, плюсы и минусы">
<title>Бурение и водоснабжение</title>
{% endblock head %}
{% block content %}
<div class="container-fluid ps-5 py-3" style="background: rgb(255,255,255);
background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgb(0, 132, 255) 100%);">
    <div class="container">
        <h1 style="font-weight: bold;">БУРЕНИЕ</h1>
    </div>
</div>
<div class="container about-text py-3">
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quam quas incidunt sunt perferendis beatae consequuntur
        exercitationem, accusantium dignissimos iure numquam maxime. A animi architecto accusantium. Molestias possimus
        ipsam eum nisi.</p>
    <p>Porro odio quibusdam dicta quaerat molestiae commodi consectetur hic explicabo delectus dolores, incidunt
        necessitatibus eaque tempora. Dolor nobis sunt eos maxime vitae sit repellendus unde. Nemo nam quod accusamus
        quisquam?</p>
    <p>Sit voluptatibus mollitia debitis quia delectus nam, atque libero! Autem, recusandae non accusamus expedita
        ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus
        nesciunt!</p>
<div style="overflow-x:auto;">
    <table class="table-responsive about-table">
        <thead>
            <tr>
                <th scope="col" style="font-weight:bold;text-align: center;border:2px solid rgb(0, 132, 255);background: rgb(255,255,255);
                background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(0, 132, 255) 100%);">Водоснабжение</th>
                <th colspan="2" scope="col" style="text-align: center;font-weight:bold;
                background: rgb(255,255,255);
background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(0, 132, 255) 100%);">Водоснабжение дома из скважины</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="text-align: center;width:33%;font-weight: bold;">Из колодца</td>
                <td style="text-align: center;width:33%;font-weight: bold;">На извесетняк</td>
                <td style="text-align: center;width:33%;font-weight: bold;">На песок</td>
            </tr>
            <tr>
                <td> <span style="font-weight:bold;color:green">Плюсы:</span> <br>
                    <ul>
                        <li>Дешевизна</li>
                        <li>Эстетичный внешний вид</li>
                    </ul>
                    <span style="font-weight:bold;color:red;">Минусы:</span>
                    <ul>
                        <li>Уровень воды зависит от сезонности</li>
                        <li>Плохое качество воды</li>
                        <li>Малый срок службы</li>
                    </ul>
                </td>
                <td><span style="font-weight:bold;color:green;">Плюсы:</span> <br>
                    <ul>
                        <li>Низкие затраты на установку</li>
                    </ul>
                    <span style="font-weight:bold;color:red;">Минусы:</span>
                    <ul>
                        <li>Быстро заиливается</li>
                        <li>Неопределенность залежей</li>
                        <li>Недолговечность</li>
                    </ul>
                </td>

                <td><span style="font-weight:bold;color:green">Плюсы:</span> <br>
                    <ul>
                        <li>Продолжительность службы данного источника воды самый продолжительный (около 60-ти лет).
                        </li>
                    </ul>
                    <span style="font-weight:bold;color:red;">Минусы:</span>
                    <ul>
                        <li>Дороговизна
                            монтажа</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</div>

</div>
{% endblock content %}

app/templates/app/service-sverlenie.html
{% extends "app/base.html" %}
{% load static %}
{% block head %}
<meta name="description" content="Чтобы высверлить дыру, мы нанимаем кенгуру">
<title>Сверление в компании WellDrill</title>
{% endblock head %}
{% block content %}
<div class="container-fluid ps-5 py-3" style="background: rgb(255,255,255);
background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgb(0, 132, 255) 100%);">
    <div class="container">
        <h1 style="font-weight: bold;">СВЕРЛЕНИЕ</h1>
    </div>
</div>
<div class="container about-text py-3">
    <div class="text-sverlenie">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quam quas incidunt sunt perferendis beatae
            consequuntur
            exercitationem, accusantium dignissimos iure numquam maxime. A animi architecto accusantium. Molestias
            possimus
            ipsam eum nisi. Orro odio quibusdam mollitia debiti. Ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus. Orro odio quibusdam mollitia debiti.</p>
        <div class="sverlenie-image"><img src="{% static 'app/images/XXL.jpg' %}"
                class="img-fluid img-thumbnail rounded" alt="Схема бурения скважины наглядно"></div>
        <p>Porro odio quibusdam dicta quaerat molestiae commodi consectetur hic explicabo delectus dolores, incidunt
            necessitatibus eaque tempora. Dolor nobis sunt eos maxime vitae sit repellendus unde. Nemo nam quod
            accusamus
            quisquam?</p>
        <p>Sit voluptatibus mollitia debitis quia delectus nam, atque libero! Autem, recusandae non accusamus expedita
            ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus    ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus
            nesciunt!</p>
        <p>Sit voluptatibus mollitia debitis quia delectus nam, atque libero! Autem, recusandae non accusamus expedita
            ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus
            nesciunt!</p>
        <p>Porro odio quibusdam dicta quaerat molestiae commodi consectetur hic explicabo delectus dolores, incidunt
            necessitatibus eaque tempora. Dolor nobis sunt eos maxime vitae sit repellendus unde. Nemo nam quod
            accusamus
            quisquam?    ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus</p>
        <p>Sit voluptatibus mollitia debitis quia delectus nam, atque libero! Autem, recusandae non accusamus expedita
            ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus
            nesciunt!</p>
        <p>Sit voluptatibus mollitia debitis quia delectus nam, atque libero! Autem, recusandae non accusamus expedita
            ullam, dignissimos inventore eos hic, neque rem quis? Sunt tenetur delectus nulla consequatur alias possimus
            nesciunt!</p>
        <p>Porro odio quibusdam dicta quaerat molestiae commodi consectetur hic explicabo delectus dolores, incidunt
            necessitatibus eaque tempora. Dolor nobis sunt eos maxime vitae sit repellendus unde. Nemo nam quod
            accusamus
            quisquam?</p>
    </div>

</div>
{% endblock content %}